[[libexif]]
arch = "aarch64"
git-tree-sha1 = "8ead3752b206b1fd2cebed20665d44ea442dbd36"
os = "macos"

    [[libexif.download]]
    sha256 = "18e9cb88720fb4eadd2d137dc5015a4f9902d2924c565d5a2cdd581f83e92ee9"
    url = "https://github.com/JuliaBinaryWrappers/libexif_jll.jl/releases/download/libexif-v0.6.24+0/libexif.v0.6.24.aarch64-apple-darwin.tar.gz"
[[libexif]]
arch = "aarch64"
git-tree-sha1 = "b11b29ba8b8c1cf2c8bbe81f52d218b677e8e6e5"
libc = "glibc"
os = "linux"

    [[libexif.download]]
    sha256 = "a5e00ea7e59082c4b3194e7184cb517059cb465257fea3514a90b0ff92a99a54"
    url = "https://github.com/JuliaBinaryWrappers/libexif_jll.jl/releases/download/libexif-v0.6.24+0/libexif.v0.6.24.aarch64-linux-gnu.tar.gz"
[[libexif]]
arch = "aarch64"
git-tree-sha1 = "6e53453287574e8f4cc681e622c07b379cfba746"
libc = "musl"
os = "linux"

    [[libexif.download]]
    sha256 = "b517ce051423decfde92b0c54e0b31537ed2b5eb64d12c6cba6e4da7b0bec704"
    url = "https://github.com/JuliaBinaryWrappers/libexif_jll.jl/releases/download/libexif-v0.6.24+0/libexif.v0.6.24.aarch64-linux-musl.tar.gz"
[[libexif]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ccd36cdee140a249be15e9014e1f2a13639e1a05"
libc = "glibc"
os = "linux"

    [[libexif.download]]
    sha256 = "8f7e2284cbbd2e671d937d37dbd5f2feead1f2607712577a75de5c3cf9bb2526"
    url = "https://github.com/JuliaBinaryWrappers/libexif_jll.jl/releases/download/libexif-v0.6.24+0/libexif.v0.6.24.armv6l-linux-gnueabihf.tar.gz"
[[libexif]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6c06ef7a474d80c6b3f492b76e6f1e3081436fe2"
libc = "musl"
os = "linux"

    [[libexif.download]]
    sha256 = "9506240b4e141f6cde7d8481e0d4bea94930ed3854aa6bbd410eb880c8e8e24a"
    url = "https://github.com/JuliaBinaryWrappers/libexif_jll.jl/releases/download/libexif-v0.6.24+0/libexif.v0.6.24.armv6l-linux-musleabihf.tar.gz"
[[libexif]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dddac54abf3c4c22eee7d56610113c7c6dd26105"
libc = "glibc"
os = "linux"

    [[libexif.download]]
    sha256 = "f7290971fc7501e64f61c1ddeb4e7212ce57f36c6853f46618b6783cd396827e"
    url = "https://github.com/JuliaBinaryWrappers/libexif_jll.jl/releases/download/libexif-v0.6.24+0/libexif.v0.6.24.armv7l-linux-gnueabihf.tar.gz"
[[libexif]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1807b8043d202a1ad6745fc2687367ae072d155d"
libc = "musl"
os = "linux"

    [[libexif.download]]
    sha256 = "350b110f191c29718bb44faeaa12a7c2e6a22d24dafca955f06b608053225208"
    url = "https://github.com/JuliaBinaryWrappers/libexif_jll.jl/releases/download/libexif-v0.6.24+0/libexif.v0.6.24.armv7l-linux-musleabihf.tar.gz"
[[libexif]]
arch = "i686"
git-tree-sha1 = "88d851e23134b51adc4493372b1525ec395777ce"
libc = "glibc"
os = "linux"

    [[libexif.download]]
    sha256 = "13ff3650f9b327b63a88f39ca9f58f03e5b79a3c918d2447e485950962d716b1"
    url = "https://github.com/JuliaBinaryWrappers/libexif_jll.jl/releases/download/libexif-v0.6.24+0/libexif.v0.6.24.i686-linux-gnu.tar.gz"
[[libexif]]
arch = "i686"
git-tree-sha1 = "9331866e1fd102f4b4ebdaba4638748be2a86d53"
libc = "musl"
os = "linux"

    [[libexif.download]]
    sha256 = "c07358e3016857b801cacea09710978b0584077bdcd9defa9c67d7cacf20e8ef"
    url = "https://github.com/JuliaBinaryWrappers/libexif_jll.jl/releases/download/libexif-v0.6.24+0/libexif.v0.6.24.i686-linux-musl.tar.gz"
[[libexif]]
arch = "i686"
git-tree-sha1 = "f258402ca68b326dd0637800b3efe3b2f44201a4"
os = "windows"

    [[libexif.download]]
    sha256 = "93182ef6fe692f93dad1e167537fa576f0d73c64a2df2076af40314a8e28fdf7"
    url = "https://github.com/JuliaBinaryWrappers/libexif_jll.jl/releases/download/libexif-v0.6.24+0/libexif.v0.6.24.i686-w64-mingw32.tar.gz"
[[libexif]]
arch = "powerpc64le"
git-tree-sha1 = "588001b7d67ef05eb94492a69169c02ad5fb2699"
libc = "glibc"
os = "linux"

    [[libexif.download]]
    sha256 = "878b180ad0f96ab3e8e5dca659643f2f0756097d45de55848c09e319bd62d337"
    url = "https://github.com/JuliaBinaryWrappers/libexif_jll.jl/releases/download/libexif-v0.6.24+0/libexif.v0.6.24.powerpc64le-linux-gnu.tar.gz"
[[libexif]]
arch = "x86_64"
git-tree-sha1 = "2c1e67277ecad23b11c50d3f1ef33f0c67cd2149"
os = "macos"

    [[libexif.download]]
    sha256 = "c95789963ec14ad9b99e6c35c377c2e96ca3fae96481d1e0fd4d7ae3828aefbd"
    url = "https://github.com/JuliaBinaryWrappers/libexif_jll.jl/releases/download/libexif-v0.6.24+0/libexif.v0.6.24.x86_64-apple-darwin.tar.gz"
[[libexif]]
arch = "x86_64"
git-tree-sha1 = "2fb84d64ecbbb4f4149590221f6d36b42bd14e05"
libc = "glibc"
os = "linux"

    [[libexif.download]]
    sha256 = "f5d22c9c852b9d75b1ec7b9d0990750b4a8fd826882fc7de924dd9ff9ebc8bd3"
    url = "https://github.com/JuliaBinaryWrappers/libexif_jll.jl/releases/download/libexif-v0.6.24+0/libexif.v0.6.24.x86_64-linux-gnu.tar.gz"
[[libexif]]
arch = "x86_64"
git-tree-sha1 = "e5c2f60ca58e17bf59811d089affb82ff59ca789"
libc = "musl"
os = "linux"

    [[libexif.download]]
    sha256 = "658796690730f545799143383a98452b2e9c52481880064908b4cb09fc6a66a7"
    url = "https://github.com/JuliaBinaryWrappers/libexif_jll.jl/releases/download/libexif-v0.6.24+0/libexif.v0.6.24.x86_64-linux-musl.tar.gz"
[[libexif]]
arch = "x86_64"
git-tree-sha1 = "79a454bfcf43b8ed171776cfe417b62bbfb2739a"
os = "freebsd"

    [[libexif.download]]
    sha256 = "963f0c596807409e582a955dc73743e7a64dfba7316324beb2221b2de95f8d84"
    url = "https://github.com/JuliaBinaryWrappers/libexif_jll.jl/releases/download/libexif-v0.6.24+0/libexif.v0.6.24.x86_64-unknown-freebsd.tar.gz"
[[libexif]]
arch = "x86_64"
git-tree-sha1 = "b536612401f6fff60fad0b43a4d22c0cc7afd6c2"
os = "windows"

    [[libexif.download]]
    sha256 = "37d884b3deadfed7d8776b199d75d2feefb8345707eb30163f947c50a6d824b6"
    url = "https://github.com/JuliaBinaryWrappers/libexif_jll.jl/releases/download/libexif-v0.6.24+0/libexif.v0.6.24.x86_64-w64-mingw32.tar.gz"
