# Autogenerated wrapper script for libexif_jll for x86_64-apple-darwin
export libexif

JLLWrappers.@generate_wrapper_header("libexif")
JLLWrappers.@declare_library_product(libexif, "@rpath/libexif.12.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libexif,
        "lib/libexif.12.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
